version: '3.6'

services:
  ms-postgres:
    image: ms-postgres
    container_name: ms-postgres
    ports:
      - "5432:5432"
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres"]
       interval: 10s
       timeout: 5s
       retries: 5
