-- Ajout de fonction   

INSERT INTO T_FONCTION(F_ID, F_CODE, F_LIBELLE) VALUES (nextval('FONCTION_SEQ'),'AJOUTER_MESSAGE','Ajouter un message');
INSERT INTO T_FONCTION(F_ID, F_CODE, F_LIBELLE) VALUES (nextval('FONCTION_SEQ'),'CONSULTER_MESSAGE','Consulter un message');
INSERT INTO T_FONCTION(F_ID, F_CODE, F_LIBELLE) VALUES (nextval('FONCTION_SEQ'),'MODIFIER_MESSAGE','Modifier un message');
INSERT INTO T_FONCTION(F_ID, F_CODE, F_LIBELLE) VALUES (nextval('FONCTION_SEQ'),'SUPPRIMER_MESSAGE','Supprimer un message');

-- Ajout de role - fonction  
INSERT INTO T_ROLE_FONCTION(ROLE_ID,FONCTION_ID)
	SELECT ROL.R_ID,FONC.F_ID
	FROM T_ROLE ROL,T_FONCTION FONC
	WHERE ROL.R_CODE='ADMIN'
	AND FONC.F_CODE IN ('AJOUTER_MESSAGE','CONSULTER_MESSAGE','MODIFIER_MESSAGE','SUPPRIMER_MESSAGE');


INSERT INTO T_ROLE_FONCTION(ROLE_ID,FONCTION_ID)
	SELECT ROL.R_ID,FONC.F_ID
	FROM T_ROLE ROL,T_FONCTION FONC
	WHERE ROL.R_CODE='USERS'
	AND FONC.F_CODE IN ('AJOUTER_MESSAGE','CONSULTER_MESSAGE','MODIFIER_MESSAGE','SUPPRIMER_MESSAGE');